### ISSUE TITLE
Dependency on XML::LibXML may be blocking usage in MacOS

### ISSUE THREAD

**Issue by balajirama** [Corion/mime-detect#4]
Hi. I am interested in trying your module. Unfortunately however, your module depends on XML::LibXML and that won't install on my system. Is it possible to do this without that so that your software is more portable?

**Comment by Corion** [comment]
Of course it is possible to remove the reliance on XML::LibXML, but I won't implement that.

How does XML::LibXML fail to install on your operating system? Usually, it is already packaged by the OS vendor or you just need to install the `libxml2-devel` package and then you can install XML::LibXML.

**Comment by balajirama** [comment]
While installing your module using `cpanm`, I find that the installation fails for missing `XML::LibXML` and that fails due to missing `Alien::Libxml2`. The following error message is seen:

Failed test 'xs'
at t/alien_libxml2.t line 10.
   ExtUtils::CBuilder->compile failed
     error building testalienUNRdy/test.o from 'testalienUNRdy/test.c' at /usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/ExtUtils/CBuilder/Base.pm line 185.
     cc -I/usr/local/Cellar/perl/5.28.1/lib/perl5/5.28.1/darwin-thread-multi-2level/CORE -c -fno-common -DPERL_DARWIN -mmacosx-version-min=10.14 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -O3 -o testalienUNRdy/test.o testalienUNRdy/test.c
     testalienUNRdy/test.xs:5:10: fatal error: 'libxml/parser.h' file not found
     #include <libxml/parser.h>
              ^~~~~~~~~~~~~~~~~
     1 error generated.
t/alien_libxml2.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 

Test Summary Report
-------------------
t/alien_libxml2.t (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=2, Tests=4,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.58 cusr  0.13 csys =  0.73 CPU)
Result: FAIL
Failed 1/2 test programs. 1/4 subtests failed.
make: *** [test_dynamic] Error 1

I'm sure this is the reason why your CPAN tester's report shows that darwin systems have not even tested your module yet. This probably means that `XML::LibXML` does not easily install on darwin systems.

**Comment by Corion** [comment]
Thank you for pursuing this a bit futher!

This is an issue with XML::LibXML or Alien::LibXML2. I cannot do anything about these libraries and their issues on OSX. I do not use OSX and don't have the knowledge nor the access to a machine where I could reproduce the situation. Please raise the issue with shlomif,  the current maintainer of XML::LibXML, or with Graham Ollis, the author of Alien::LibXML2 ( also at https://github.com/Perl5-Alien/Alien-Libxml2 ). Maybe opening an issue there helps them fix the problems on OSX.
